# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vipspad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Vipspad
  pod 'Alamofire'
  pod 'KeychainSwift'
  pod "ToastViewSwift"
  pod 'FirebaseMessaging'
  pod 'FirebaseCore'
  target 'VipspadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VipspadUITests' do
    # Pods for testing
  end

end
